## Array using List in Python

In [1]:
# insert 3 at index 0
lst = [1, 3, 4, 5, 6, 8]
lst.insert(0, 3)
lst

[3, 1, 3, 4, 5, 6, 8]

In [7]:
# to remove the item from the list
lst.remove(3)

In [8]:
lst

[3, 5, 6, 8]

In [9]:
# remove/ pop the element from the index 
lst.pop(2)  # pops the index 2 element from the list
lst

[3, 5, 8]


    Let us say your expense for every month are listed below,
        January - 2200
        February - 2350
        March - 2600
        April - 2130
        May - 2190

Create a list to store these monthly expenses and using that find out,
1. In Feb, how many dollars you spent extra compare to January?
2. Find out your total expense in first quarter (first three months) of the year.
3. Find out if you spent exactly 2000 dollars in any month
4. June month just finished and your expense is 1980 dollar. Add this item to our monthly expense list
5. You returned an item that you bought in a month of April and
got a refund of 200$. Make a correction to your monthly expense list
based on this

In [33]:
exp = [2200, 2350, 2600, 2130, 2190]

# qn1 
print (f'In Feb {exp[1]-exp[0]} dollars were spend extra compared to Jan')

#qn2
print(f'The total expense in first quarter of the year is {exp[0]+exp[1]+exp[2]} dollars')

#qn3
if 2000 in exp:
    print("True")
else:
    print("false")

#qn4
exp.append(1980)
print(f'expense of june is {exp}')

#qn 5
exp[3] = exp[3] - 200
exp[3]

In Feb 150 dollars were spend extra compared to Jan
The total expense in first quarter of the year is 7150 dollars
false
expense of june is [2200, 2350, 2600, 2130, 2190, 1980]


1930


    You have a list of your favourite marvel super heros.

heros=['spider man','thor','hulk','iron man','captain america']

Using this find out,

1. Length of the list
2. Add 'black panther' at the end of this list
3. You realize that you need to add 'black panther' after 'hulk',
   so remove it from the list first and then add it after 'hulk'
4. Now you don't like thor and hulk because they get angry easily :)
   So you want to remove thor and hulk from list and replace them with doctor strange (because he is cool).
   Do that with one line of code.
5. Sort the heros list in alphabetical order (Hint. Use dir() functions to list down all functions available in list)


In [50]:
heros=['spider man','thor','hulk','iron man','captain america']

# #qn 1
print('The length of the list is', len(heros))

# # qn 2
heros.append('black panther')
print (heros)

#qn 3

heros.insert(3, 'black panther')
print(heros)

#qn 4
heros[1:3] = ['doctor strange']
print (heros)

#qn 5
heros.sort()
print(heros)

The length of the list is 5
['spider man', 'thor', 'hulk', 'iron man', 'captain america', 'black panther']
['spider man', 'thor', 'hulk', 'black panther', 'iron man', 'captain america', 'black panther']
['spider man', 'doctor strange', 'black panther', 'iron man', 'captain america', 'black panther']
['black panther', 'black panther', 'captain america', 'doctor strange', 'iron man', 'spider man']


### Create a list of all odd numbers between 1 and a max number. Max number is something you need to take from a user using input() function

In [1]:
x = int(input("Enter the max number"))
odd_numbers = []
for i in range(1, x):
    if (i%2 != 0):
        odd_numbers.append[i]
    
print("Odd numbers", odd_numbers)

# Arrays using Numpy

In [1]:
import numpy as np

In [4]:
# creating numpy arrays from python list
lst = [1, 45, 6,7, 1, 4]
arr= np.array(lst)
arr

array([ 1, 45,  6,  7,  1,  4])

In [5]:
# we can explicitly set the datatype of the numpy array using dtype= '' keyword
arr = np.array(lst, dtype='float')
arr

array([ 1., 45.,  6.,  7.,  1.,  4.])

In [7]:
#unlike python lists, we can create multi dimensional arrays using numpy 

arr1 = np.array([range(i, i+3) for i in [1, 3, 5]])
arr1


array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [23]:
# creating arrays from scratch 

print(f'{np.zeros(10, dtype=int)} : This creates a length-10 integer array filled with zeros')
print('\n') 
print(f'{np.ones((3, 6), dtype= float)}  : This creats a 3x6 array filled with ones' )
print('\n') 
print(f'{np.full((3, 5), 3.14)}:  This creates a 3x5 array filled with 3.14')
print('\n') 
print(f'{np.arange(0, 20, 2)}:  This creats an array starting at 0 , ending at 20 with step 2 FILLED WITH LINEAR SEQUENCE' )
print('\n') 
print(f'{np.random.random((2,2))}')
print('\n') 
print(f'{np.random.normal(0, 1, (3, 3))}: creates a 3x3 array of normally distributed random values with MEAN 0 AND STARNDARD DEVIATION 1')


[0 0 0 0 0 0 0 0 0 0] : This creates a length-10 integer array filled with zeros


[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]  : This creats a 3x6 array filled with ones


[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]:  This creates a 3x5 array filled with 3.14


[ 0  2  4  6  8 10 12 14 16 18]:  This creats an array starting at 0 , ending at 20 with step 2 FILLED WITH LINEAR SEQUENCE


[[0.15059446 0.23165522]
 [0.17616386 0.21891891]]


[[-0.06780365 -0.0164108   0.45031739]
 [-0.30012767 -0.72920579 -0.03470194]
 [-1.53177953 -1.31346055 -0.07483209]]: creates a 3x3 array of normally distributed random values with MEAN 0 AND STARNDARD DEVIATION 1


In [31]:
random_array = np.arange(1, 5, 1)
random_array.mean()
random_array.max()

4

### BASIC ARRAY MANIPULATION

- *Attributes of arrays*: Determining the size, shape, memory consumption, and data types of arrays
- *Indexing of arrays*: Getting and setting the value of individual array elements
- *Slicing of arrays*: Getting and setting smaller subarrays within a larger array
- *Reshaping of arrays*: Changing the shape of a given array
- *Joining and splitting of arrays*: Combining multiple arrays into one, and splitting one array into many

### Numpy Array attributes

In [46]:
np.random.seed(0)   #seed for reprducibility
x1 = np.random.randint(10, size=6)      # 1D array ; here 10 means random integers upto 10
x2 = np.random.randint(10, size= (3, 4))  # 2D array
x3 = np.random.randint(10, size = (3, 4, 5))  # 3D array

each array has attribute ndim (number of dimensions), shape (size of each dimension), and size (total size of an array)

In [47]:
print(x1)
print("x1 ndim", x1.ndim)
print("x1 shape", x1.shape)
print("x1 size", x1.size)

[12 15  0  3  3  7]
x1 ndim 1
x1 shape (6,)
x1 size 6


In [44]:
print(x2)
print("x2 ndim: ", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
x2 ndim:  2
x2 shape: (3, 4)
x2 size:  12


In [43]:
print(x3)
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


other attributes include "dtype", "itemsize" and "nbytes"


In [49]:
print(x1)
print("dtype", x1.dtype)
print("itemsize:", x1.itemsize, "bytes")    # itemsize=  size in bytes of each member of the array
print("nbytes:", x1.nbytes, "bytes")        # nbytes =  size in bytes of entire array

[12 15  0  3  3  7]
dtype int32
itemsize: 4 bytes
nbytes: 24 bytes


### Array indexing

Same concept as that of standard python list indexing

In [63]:
# one thing to keep in mind:  since arrays only support elements of same datatypes, explicit entry of element with different datatype will result
# into value being truncated 

arr = np.random.randint(10, size= 5, dtype = "int")
print("random array",arr)


random array [8 3 8 2 8]


In [64]:
arr[3] =3.1415   # the value is truncated 
print(arr)

[8 3 8 3 8]


### ARRAY SLICING

syntax:
x[start: stop: step]

In [65]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
x[:5] # elements before index 5

array([0, 1, 2, 3, 4])

In [67]:
x[5:]  #elements after index 5

array([5, 6, 7, 8, 9])

In [68]:
x[3:8]

array([3, 4, 5, 6, 7])

In [69]:
x[::2]

array([0, 2, 4, 6, 8])

In [70]:
x[1::2]

array([1, 3, 5, 7, 9])

In [71]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [72]:
x[5::-2]

array([5, 3, 1])

In [73]:
x[:-3]

array([0, 1, 2, 3, 4, 5, 6])

### RESHAPING OF ARRAYS
Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [76]:
grid = np.arange(1, 10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
grid = grid.reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### JOINING AND SPLITTING OF ARRAY

In [80]:
X = np.array([1, 3, 4, 5, 6, 7])
Y = np.array([10, 34, 6, 84, 5])
np.concatenate([X, Y])

array([ 1,  3,  4,  5,  6,  7, 10, 34,  6, 84,  5])

In [82]:
# multiple arrays can be concatenated at once
np.concatenate([x, X, Y])   

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  1,  3,  4,  5,  6,  7, 10,
       34,  6, 84,  5])

##### Splitting of arrays

the opposite of concatenation! can be done via `np.split, np.hsplit, np.vsplit`

In [86]:
a= [1,3, 4, 5, 7, 8, 9, 34]
a1, a2, a3 = np.split(a, [3, 6])    # here we pass list of indices as an arguement i.e 1st array forms from index 0 upto 2, 2nd from 3 upto 5....
print(a1, a2, a3)

[1 3 4] [5 7 8] [ 9 34]
